-- =============================================================================
-- ccasa — esquema PostgreSQL alineado con entidades JPA (com.backend.ccasa.persistence)
-- Generado como referencia estática desde anotaciones @Table / @Column.
--
-- Uso: base de datos vacía (CREATE sin IF NOT EXISTS). Zona horaria recomendada:
--   SET TIME ZONE 'UTC';  (coherente con spring.jpa / Jackson UTC en la aplicación)
--
-- Nota: columnas de auditoría (created_by_user_id, etc.) se enlazan a app_user
--       mediante ALTER al final para evitar ciclos role ↔ app_user.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1) Núcleo identidad: role, app_user
-- -----------------------------------------------------------------------------

CREATE TABLE role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash TEXT,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT fk_app_user_role FOREIGN KEY (role_id) REFERENCES role (role_id)
);

ALTER TABLE role
    ADD CONSTRAINT fk_role_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_role_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_role_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE app_user
    ADD CONSTRAINT fk_app_user_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_app_user_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_app_user_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

-- -----------------------------------------------------------------------------
-- 2) Bitácoras, folios, catálogos
-- -----------------------------------------------------------------------------

CREATE TABLE logbook (
    logbook_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code INTEGER NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    max_entries INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT uq_logbook_code UNIQUE (code)
);

CREATE TABLE lab_reference_parameter (
    reference_parameter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    min_value NUMERIC(20, 10),
    max_value NUMERIC(20, 10),
    description TEXT,
    rule_detail TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT uq_lab_reference_parameter_code UNIQUE (code)
);

CREATE TABLE folio_block (
    folio_block_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier VARCHAR(50) NOT NULL,
    start_number INTEGER NOT NULL,
    end_number INTEGER NOT NULL,
    cover_generated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT
);

CREATE TABLE solution (
    solution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    concentration VARCHAR(50),
    quantity VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT
);

CREATE TABLE lab_equipment (
    lab_equipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type VARCHAR(80) NOT NULL,
    denomination VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT uq_lab_equipment_denomination UNIQUE (denomination)
);

CREATE TABLE supply (
    supply_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    available_qty NUMERIC(10, 2),
    unit VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT
);

CREATE TABLE reagent (
    reagent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    chemical_formula VARCHAR(50),
    unit VARCHAR(20),
    total_stock NUMERIC(10, 4),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT
);

CREATE TABLE reagent_jar (
    reagent_jar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reagent_id BIGINT NOT NULL,
    initial_amount_g NUMERIC(10, 4),
    current_amount_g NUMERIC(10, 4),
    opened_at DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_reagent_jar_reagent FOREIGN KEY (reagent_id) REFERENCES reagent (reagent_id)
);

CREATE TABLE batch (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code VARCHAR(50) NOT NULL,
    reagent_id BIGINT NOT NULL,
    generated_at DATE,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_batch_reagent FOREIGN KEY (reagent_id) REFERENCES reagent (reagent_id)
);

CREATE TABLE folio (
    folio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_block_id BIGINT NOT NULL,
    logbook_id BIGINT NOT NULL,
    folio_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_folio_folio_block FOREIGN KEY (folio_block_id) REFERENCES folio_block (folio_block_id),
    CONSTRAINT fk_folio_logbook FOREIGN KEY (logbook_id) REFERENCES logbook (logbook_id)
);

CREATE TABLE entry (
    entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_id BIGINT NOT NULL,
    logbook_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    recorded_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_entry_folio FOREIGN KEY (folio_id) REFERENCES folio (folio_id),
    CONSTRAINT fk_entry_logbook FOREIGN KEY (logbook_id) REFERENCES logbook (logbook_id),
    CONSTRAINT fk_entry_user FOREIGN KEY (user_id) REFERENCES app_user (user_id)
);

CREATE TABLE signature (
    signature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    supervisor_user_id BIGINT NOT NULL,
    signed_at TIMESTAMPTZ,
    signature_type VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_signature_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_signature_supervisor_user FOREIGN KEY (supervisor_user_id) REFERENCES app_user (user_id)
);

CREATE TABLE alert (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(80),
    message TEXT,
    generated_at TIMESTAMPTZ,
    target_user_id BIGINT,
    status VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_alert_target_user FOREIGN KEY (target_user_id) REFERENCES app_user (user_id)
);

-- -----------------------------------------------------------------------------
-- 3) Extensiones de entrada (1:1 / detalle por tipo)
-- -----------------------------------------------------------------------------

CREATE TABLE entry_distilled_water (
    distilled_water_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    ph_reading_1 NUMERIC(5, 3),
    ph_reading_2 NUMERIC(5, 3),
    ph_reading_3 NUMERIC(5, 3),
    ph_average NUMERIC(5, 3),
    ce_reading_1 NUMERIC(8, 4),
    ce_reading_2 NUMERIC(8, 4),
    ce_reading_3 NUMERIC(8, 4),
    ce_average NUMERIC(8, 4),
    reference_difference NUMERIC(6, 4),
    control_standard_pct NUMERIC(6, 2),
    is_acceptable BOOLEAN,
    water_batch_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_edw_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_edw_water_batch FOREIGN KEY (water_batch_id) REFERENCES batch (batch_id)
);

CREATE TABLE entry_conductivity (
    conductivity_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    type VARCHAR(20),
    measured_value NUMERIC(8, 4),
    weight_grams NUMERIC(12, 6),
    calculated_mol NUMERIC(10, 6),
    calculated_value NUMERIC(10, 6),
    in_range BOOLEAN,
    auto_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_ec_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id)
);

CREATE TABLE entry_oven_temp (
    oven_temp_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    raw_temperature NUMERIC(5, 2),
    corrected_temperature NUMERIC(5, 2),
    reading_number INTEGER,
    recorded_at TIMESTAMPTZ,
    in_range BOOLEAN,
    is_maintenance BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_eot_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id)
);

CREATE TABLE entry_weighing (
    weighing_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    reagent_id BIGINT,
    weight_grams NUMERIC(10, 4),
    target_solution_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_ew_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_ew_reagent FOREIGN KEY (reagent_id) REFERENCES reagent (reagent_id),
    CONSTRAINT fk_ew_target_solution FOREIGN KEY (target_solution_id) REFERENCES solution (solution_id)
);

CREATE TABLE entry_material_wash (
    material_wash_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    monday_date DATE,
    piece_type VARCHAR(20),
    material VARCHAR(100),
    determination VARCHAR(100),
    color VARCHAR(50),
    analyst_user_id BIGINT,
    supervisor_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_emw_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_emw_analyst_user FOREIGN KEY (analyst_user_id) REFERENCES app_user (user_id),
    CONSTRAINT fk_emw_supervisor_user FOREIGN KEY (supervisor_user_id) REFERENCES app_user (user_id)
);

CREATE TABLE entry_drying_oven (
    drying_oven_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    reagent_id BIGINT,
    entry_time TIME,
    exit_time TIME,
    analyst_user_id BIGINT,
    supervisor_user_id BIGINT,
    meets_temp BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_edo_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_edo_reagent FOREIGN KEY (reagent_id) REFERENCES reagent (reagent_id),
    CONSTRAINT fk_edo_analyst_user FOREIGN KEY (analyst_user_id) REFERENCES app_user (user_id),
    CONSTRAINT fk_edo_supervisor_user FOREIGN KEY (supervisor_user_id) REFERENCES app_user (user_id)
);

CREATE TABLE entry_accuracy (
    accuracy_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    sampler_user_id BIGINT,
    batch_1_avg NUMERIC(8, 4),
    batch_2_avg NUMERIC(8, 4),
    difference NUMERIC(8, 4),
    in_range BOOLEAN,
    ph_logbook_id BIGINT,
    ph_folio_number INTEGER,
    daily_record_date DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_ea_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_ea_sampler_user FOREIGN KEY (sampler_user_id) REFERENCES app_user (user_id),
    CONSTRAINT fk_ea_ph_logbook FOREIGN KEY (ph_logbook_id) REFERENCES logbook (logbook_id)
);

CREATE TABLE entry_flask_treatment (
    flask_treatment_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    wash_entry_id BIGINT,
    swab_supply_id BIGINT,
    swabs_used INTEGER,
    analysis_value NUMERIC(8, 4),
    cmc_result VARCHAR(20),
    report_date DATE,
    supervisor_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_eft_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_eft_wash_entry FOREIGN KEY (wash_entry_id) REFERENCES entry_material_wash (material_wash_entry_id),
    CONSTRAINT fk_eft_swab_supply FOREIGN KEY (swab_supply_id) REFERENCES supply (supply_id),
    CONSTRAINT fk_eft_supervisor_user FOREIGN KEY (supervisor_user_id) REFERENCES app_user (user_id)
);

CREATE TABLE entry_expense_chart (
    expense_chart_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    employment_date DATE,
    end_date DATE,
    equipment_key VARCHAR(50),
    distilled_water_qty NUMERIC(8, 2),
    water_type VARCHAR(30),
    batch_id BIGINT,
    kcl_jar_id BIGINT,
    kcl_used_g NUMERIC(10, 4),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_eec_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_eec_batch FOREIGN KEY (batch_id) REFERENCES batch (batch_id),
    CONSTRAINT fk_eec_kcl_jar FOREIGN KEY (kcl_jar_id) REFERENCES reagent_jar (reagent_jar_id)
);

CREATE TABLE entry_solution_prep (
    solution_prep_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    solution_id BIGINT NOT NULL,
    weighing_entry_id BIGINT,
    analyst_user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT,
    updated_by_user_id BIGINT,
    deleted_by_user_id BIGINT,
    CONSTRAINT fk_esp_entry FOREIGN KEY (entry_id) REFERENCES entry (entry_id),
    CONSTRAINT fk_esp_solution FOREIGN KEY (solution_id) REFERENCES solution (solution_id),
    CONSTRAINT fk_esp_weighing_entry FOREIGN KEY (weighing_entry_id) REFERENCES entry_weighing (weighing_entry_id),
    CONSTRAINT fk_esp_analyst_user FOREIGN KEY (analyst_user_id) REFERENCES app_user (user_id)
);

-- -----------------------------------------------------------------------------
-- 4) Auditoría: FKs hacia app_user (tablas que extienden Auditable)
-- -----------------------------------------------------------------------------

ALTER TABLE logbook
    ADD CONSTRAINT fk_logbook_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_logbook_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_logbook_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE lab_reference_parameter
    ADD CONSTRAINT fk_lab_reference_parameter_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_lab_reference_parameter_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_lab_reference_parameter_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE folio_block
    ADD CONSTRAINT fk_folio_block_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_folio_block_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_folio_block_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE solution
    ADD CONSTRAINT fk_solution_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_solution_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_solution_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE lab_equipment
    ADD CONSTRAINT fk_lab_equipment_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_lab_equipment_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_lab_equipment_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE supply
    ADD CONSTRAINT fk_supply_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_supply_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_supply_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE reagent
    ADD CONSTRAINT fk_reagent_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_reagent_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_reagent_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE reagent_jar
    ADD CONSTRAINT fk_reagent_jar_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_reagent_jar_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_reagent_jar_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE batch
    ADD CONSTRAINT fk_batch_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_batch_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_batch_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE folio
    ADD CONSTRAINT fk_folio_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_folio_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_folio_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry
    ADD CONSTRAINT fk_entry_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_entry_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_entry_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE signature
    ADD CONSTRAINT fk_signature_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_signature_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_signature_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE alert
    ADD CONSTRAINT fk_alert_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_alert_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_alert_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_distilled_water
    ADD CONSTRAINT fk_edw_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_edw_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_edw_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_conductivity
    ADD CONSTRAINT fk_ec_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_ec_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_ec_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_oven_temp
    ADD CONSTRAINT fk_eot_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_eot_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_eot_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_weighing
    ADD CONSTRAINT fk_ew_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_ew_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_ew_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_material_wash
    ADD CONSTRAINT fk_emw_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_emw_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_emw_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_drying_oven
    ADD CONSTRAINT fk_edo_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_edo_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_edo_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_accuracy
    ADD CONSTRAINT fk_ea_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_ea_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_ea_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_flask_treatment
    ADD CONSTRAINT fk_eft_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_eft_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_eft_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_expense_chart
    ADD CONSTRAINT fk_eec_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_eec_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_eec_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

ALTER TABLE entry_solution_prep
    ADD CONSTRAINT fk_esp_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_esp_updated_by_user FOREIGN KEY (updated_by_user_id) REFERENCES app_user (user_id),
    ADD CONSTRAINT fk_esp_deleted_by_user FOREIGN KEY (deleted_by_user_id) REFERENCES app_user (user_id);

-- -----------------------------------------------------------------------------
-- 5) Índices (FKs y consultas habituales con soft delete)
-- -----------------------------------------------------------------------------

CREATE INDEX idx_entry_logbook_deleted ON entry (logbook_id, deleted_at);
CREATE INDEX idx_entry_folio_id ON entry (folio_id);
CREATE INDEX idx_entry_user_id ON entry (user_id);
CREATE INDEX idx_folio_logbook_deleted ON folio (logbook_id, deleted_at);
CREATE INDEX idx_folio_block_id ON folio (folio_block_id);
CREATE INDEX idx_signature_entry_id ON signature (entry_id);
CREATE INDEX idx_alert_target_user_id ON alert (target_user_id);
CREATE INDEX idx_batch_reagent_id ON batch (reagent_id);
CREATE INDEX idx_reagent_jar_reagent_id ON reagent_jar (reagent_id);
CREATE INDEX idx_lab_reference_parameter_code ON lab_reference_parameter (code) WHERE deleted_at IS NULL;
CREATE INDEX idx_lab_equipment_type ON lab_equipment (equipment_type) WHERE deleted_at IS NULL;

CREATE INDEX idx_edw_entry_id ON entry_distilled_water (entry_id);
CREATE INDEX idx_ec_entry_id ON entry_conductivity (entry_id);
CREATE INDEX idx_eot_entry_recorded ON entry_oven_temp (entry_id, recorded_at);
CREATE INDEX idx_ew_entry_id ON entry_weighing (entry_id);
CREATE INDEX idx_emw_entry_id ON entry_material_wash (entry_id);
CREATE INDEX idx_edo_entry_id ON entry_drying_oven (entry_id);
CREATE INDEX idx_ea_entry_id ON entry_accuracy (entry_id);
CREATE INDEX idx_eft_entry_id ON entry_flask_treatment (entry_id);
CREATE INDEX idx_eec_entry_id ON entry_expense_chart (entry_id);
CREATE INDEX idx_esp_entry_id ON entry_solution_prep (entry_id);

-- -----------------------------------------------------------------------------
-- 6) Comentarios (tablas y columnas clave)
-- -----------------------------------------------------------------------------

COMMENT ON TABLE logbook IS 'Bitácora de laboratorio (catálogo por código).';
COMMENT ON TABLE lab_reference_parameter IS 'Límites y tolerancias de laboratorio (RF-05, RF-06, etc.) para cálculos en aplicación.';
COMMENT ON COLUMN lab_reference_parameter.rule_detail IS 'Descripción semántica de la regla o fórmula aplicada en el módulo correspondiente.';
COMMENT ON TABLE lab_equipment IS 'Catálogo de equipos de laboratorio (activos).';
COMMENT ON TABLE folio IS 'Folio físico/digital asociado a una bitácora y a un bloque de folios.';
COMMENT ON TABLE entry IS 'Registro genérico en bitácora; el tipo de detalle se materializa en tablas entry_* .';
COMMENT ON TABLE signature IS 'Firma de supervisor sobre una entrada (distinto del autor).';
COMMENT ON COLUMN entry.deleted_at IS 'Borrado lógico; las consultas de negocio filtran deleted_at IS NULL.';
COMMENT ON COLUMN app_user.password_hash IS 'Hash de contraseña; no almacenar texto plano.';

COMMIT;
