# -*- coding: utf-8 -*-
"""Lista de archivos Excel analizados (compartida por analyze_excel.py y extract_excel_formulas.py)."""
from pathlib import Path

# Raíz del repo: usar variable de entorno CCASA_ROOT o directorio padre del manifiesto
REPO_ROOT = Path(__file__).resolve().parent
BASE = Path(__file__).resolve().parent / "filesproyect"

FILES = [
    "1-AGUA DESTILADA 1-MT/1-MT-02 AGUA DESTILADA.xlsx",
    "1-AGUA DESTILADA 1-MT/1-MT-03 AGUA DESTILADA.xlsx",
    "2-CONDUCTIVIDAD ALTA/1-AGUA DESTILADA 1-MT/1-MT-02 AGUA DESTILADA.xlsx",
    "2-CONDUCTIVIDAD ALTA/1-AGUA DESTILADA 1-MT/1-MT-03 AGUA DESTILADA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-108 --CONDUCTIVIDAD ALTA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-109 --CONDUCTIVIDAD ALTA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-110 --CONDUCTIVIDAD ALTA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-111 --CONDUCTIVIDAD ALTA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-112 --CONDUCTIVIDAD ALTA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-113 --CONDUCTIVIDAD ALTA.xlsx",
    "2-CONDUCTIVIDAD ALTA/20-114 --CONDUCTIVIDAD ALTA.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-108-01 --CONDUCTIVIDAD BAJAS.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-109 -01--CONDUCTIVIDAD BAJAS.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-110-01 --CONDUCTIVIDAD BAJAS.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-111-01- --CONDUCTIVIDAD BAJA BCN.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-111-01-CONDUCTIVIDAD BAJA.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-112-01-CONDUCTIVIDAD BAJA.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-113-01-CONDUCTIVIDAD BAJA.xlsx",
    "3-CONDUCTIVIDAD BAJA/20-114-01-CONDUCTIVIDAD BAJA.xlsx",
    "4 Y 5-GASTOS/CE/Carta de gastos conductividad.xlsx",
    "4 Y 5-GASTOS/PH/Carta de gastos pH.xlsx",
    "6-CARTA CONTROL HORNO DE SECADO/Control de temperatura horno 2024-2025.xlsx",
    "6-CARTA CONTROL HORNO DE SECADO/Control de temperatura horno 2026.xlsx",
    "11-REGISTRO HORNO SECADO M-HS/M-HS-01 Uso horno de secado.xlsx",
    "12-LAVADO MATERIAL M-LM/M-LM-01 Lavado de material.xlsx",
    "14-PREPARACION SOLUCIONES M-SOL/M-SOL- 01 PREPARACION DE SOLUCIONES..xlsx",
    "14-PREPARACION SOLUCIONES M-SOL/M-SOL- 02 PREPARACION DE SOLUCIONES..xlsx",
    "Listados.xlsx",
]
